/*
 * generated by Xtext 2.22.0
 */
package lu.uni.lassy.phd.dsl.semkis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SemkisUiModule extends AbstractSemkisUiModule {

	public SemkisUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
