/*
 * generated by Xtext 2.22.0
 */
package lu.uni.lassy.phd.dsl.semkis.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lu.uni.lassy.phd.dsl.semkis.SemkisRuntimeModule;
import lu.uni.lassy.phd.dsl.semkis.SemkisStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SemkisIdeSetup extends SemkisStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SemkisRuntimeModule(), new SemkisIdeModule()));
	}
	
}
