/*
 * generated by Xtext 2.22.0
 */
package lu.uni.lassy.phd.dsl.semkis.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SemkisScopeProvider extends AbstractSemkisScopeProvider {

}
