/*
 * generated by Xtext 2.22.0
 */
package lu.uni.lassy.phd.dsl.semkis;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SemkisRuntimeModule extends AbstractSemkisRuntimeModule {
}
