/*
 * generated by Xtext 2.22.0
 */
package lu.uni.lassy.phd.dsl.semkis;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SemkisStandaloneSetup extends SemkisStandaloneSetupGenerated {

	public static void doSetup() {
		new SemkisStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
