/*
 * generated by Xtext 2.22.0
 */
package lu.uni.lassy.phd.dsl.semkis.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SemkisProposalProvider extends AbstractSemkisProposalProvider {
}
